name: Install Mops
description: Install Mops with caching for faster subsequent builds
inputs:
  mops-version:
    description: Mops CLI version to install
    default: latest
  moc-version:
    description: >
      Install specific moc version
      Equivalent to `mops toolchain use moc <version>`
  wasmtime-version:
    description: >
      Install specific wasmtime version
      Equivalent to `mops toolchain use wasmtime <version>`
  pocket-ic-version:
    description: >
      Install specific pocket-ic version
      Equivalent to `mops toolchain use pocket-ic <version>`
  identity-pem:
    description: >
      Identity PEM to import.
      Use GitHub Secrets to store the PEM, do not paste it directly here.
      Use only when you need to publish a package to the mops registry.

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache mops packages and toolchain
      uses: actions/cache@v4
      with:
        key: mops-cache-${{ hashFiles('mops.toml') }}
        restore-keys: |
          mops-cache-${{ hashFiles('mops.toml') }}
          mops-cache-
        path: ~/.cache/mops

    - name: Set env var
      shell: sh
      env:
        MOPS_VERSION: ${{ inputs['mops-version'] }}
      run: |
        echo "MOPS_VERSION=$MOPS_VERSION";
        if echo "$MOPS_VERSION" | grep -Eq '^[^.]+\.[^.]+\.[^.]+$' || echo "$MOPS_VERSION" | grep -Eq '^[^.]+$'; then
          echo "INSTALL_ONCHAIN=true" >> $GITHUB_ENV
        else
          echo "INSTALL_ONCHAIN=false" >> $GITHUB_ENV
        fi

    - name: Install mops (onchain storage)
      if: env.INSTALL_ONCHAIN == 'true'
      env:
        MOPS_VERSION: ${{ inputs['mops-version'] }}
      shell: sh
      run: curl -fsSL cli.mops.one/install.sh | sh

    - name: Install mops (npm registry)
      if: env.INSTALL_ONCHAIN == 'false'
      shell: sh
      run: npm i -g ic-mops@${{ inputs.mops-version }}

    - name: Check mops version
      shell: sh
      run: mops --version

    - name: Install moc
      if: ${{ inputs.moc-version }}
      shell: sh
      run: mops toolchain use moc ${{ inputs.moc-version }}

    - name: Install wasmtime
      if: ${{ inputs.wasmtime-version }}
      shell: sh
      run: mops toolchain use wasmtime ${{ inputs.wasmtime-version }}

    - name: Install pocket-ic
      if: ${{ inputs.pocket-ic-version }}
      shell: sh
      run: mops toolchain use pocket-ic ${{ inputs.pocket-ic-version }}

    - name: Import identity
      if: ${{ inputs.identity-pem }}
      shell: sh
      run: mops import-identity --no-encrypt -- "${{ inputs.identity-pem }}"

    - name: Ensure moc installation for publishing
      if: ${{ ! inputs.moc-version && inputs.identity-pem }}
      shell: sh
      run: mops toolchain bin moc || mops toolchain use moc latest