on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test-self:
    name: Test action.yml
    strategy:
      matrix:
        mops-version: [0.39, 0.41.1, latest]
        wasmtime-version: [15.0.0, 24.0.0]
        pocket-ic-version: [1.0.0, 5.0.0]
        runner: [ubuntu-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Install mops
        uses: ./
        with:
          mops-version: ${{ matrix.mops-version }}
          wasmtime-version: ${{ matrix.wasmtime-version }}
          pocket-ic-version: ${{ matrix.pocket-ic-version }}
      - name: Check mops version
        run: mops --version
      - name: Check moc path
        run: mops toolchain bin moc
      - name: Check moc version
        run: $(mops toolchain bin moc) --version
      - name: Check wasmtime path
        run: mops toolchain bin wasmtime
      - name: Check wasmtime version
        run: $(mops toolchain bin wasmtime) --version
      - name: Check pocket-ic path
        run: mops toolchain bin pocket-ic
      - name: Check pocket-ic version
        run: $(mops toolchain bin pocket-ic) --version